### PR TITLE
Hello Microverse Project Pull Request

### PR DESCRIPTION
**Pull request by Fene-87**
This is a simple Microverse project covering basic HTML and CSS and most importantly using linters for HTML CSS

### CODE REVIEW

**Review by Gopxfs — CHANGES_REQUESTED** [review]
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @Fene-87 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights :rocket:
✔️ No linter errors.
✔️ Great folder structure. Well done!
✔️ Correct GitHub flow.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
Hello @Fene-87, you did a pretty solid job with your first project! Well done 😄! Please consider the following changes on your readme file 😉:
- You did a good job describing the project, please also add the correct title "Hello Microverse" instead of "Microverse Linters".
image

- Nice job adding the correct links! Kindly consider changing the name of your links to your name. Something like this:
[@Fene-87](https://github.com/Fene-87)
image

- The link to your MIT document isn't working 😃. Please make sure to check all your links paths. 
image

Keep in mind that the Readme is the showcase of your project, you can use templates but don't forget to personalize them 😉.

**Comment by Gopxfs** [comment]
In case you need help managing your links, to do so, select a piece of the sentence: 
image

A sentence with a [link](https://github.com/Gopxfs).

And paste the link (CTRL + V). It will automatically format everything for you 😉: 
image

The text between [ ] can be personalized, and the one between ( ) is where the user will be redirected.

Cheers and keep coding 😄.

**Comment by Fene-87** [comment]
Thanks @Gopxfs for your review. Is it okay if I got rid of the License link altogether for this project?

**Comment by RiyaBulia12** [comment]
> Thanks @Gopxfs for your review. Is it okay if I got rid of the License link altogether for this project?

Hello @Fene-87, great job applying all the changes. 👏🏽  One more change and you are all set. 😉  Kindly put the MIT license back in your readme as it recommended using the [MIT license](https://choosealicense.com/licenses/mit/).

**Review by RiyaBulia12 — CHANGES_REQUESTED** [review]
## Hi @Fene-87 👋🏽 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
so close

## Highlights
✔️ No linters
✔️ Correct Github Flow
✔️ Meaningful commit messages


## Required Changes ♻️
- [ ] Great job on applying the requested changes 👏🏽 There is one small change in your readme file. Kindly go through the following steps to add your LICENSE to your project as it is recommended using the [MIT license](https://choosealicense.com/licenses/mit/) 
 * Please add a LICENSE.md file in your project root folder and add [this content](https://github.com/microverseinc/readme-template/blob/master/MIT.md) in your file and modify the content accordingly (for example, your name, app type) 😃 
* Kindly, add a link to your README 
> This project is [MIT](./LICENSE) licensed. 😃 
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by emmiiorji — APPROVED** [review]
Hi @Fene-87, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

congratulations

## Good Highlights✔️

- Linter checks are passing
- Requested change has been implemented
- Adhered to GitHub flow


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
